### ISSUE TITLE
Add citation section to readme

### ISSUE THREAD

**Issue by fleverest** [shinjaehyeok/stcpR6#2]
Hi, I cited this package in a report I produced for my PhD milestone. I recommend adding some suggested bibtex citation to your readme, or elsewhere. I ended up extrapolating some information based on your 2023 publication. Here's what I inevitably landed on:

```
@Manual{stcpR6,
  title = {stcpR6: Sequential Test and Change-Point detection algorithms based on E-values / E-detectors},
  author = {Shin, Jaehyeok},
  year = {2023},
  note = {R package version 0.9.6.9000},
  url = {https://github.com/shinjaehyeok/stcpR6}
}
```

**Comment by shinjaehyeok** [comment]
Thanks for the great suggestion! =) I updated README accordingly (A minor updated package is now in CRAN so I cited it)
