### ISSUE TITLE
Add topic tags

### ISSUE THREAD

**Issue by Beliavsky** [shinjaehyeok/stcpR6#4]
I suggest adding the topics `changepoint`, `timeseries`, `time-series-analysis`, `r-package` in the About section, as explained at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by shinjaehyeok** [comment]
Thanks for the great suggestion! I added some of the suggested ones.
